/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_gestion_capteur_ (void);
GtkWidget* create_ajouter_capteur (void);
GtkWidget* create_modifier_capteur (void);
GtkWidget* create_supprimer_capteur (void);
GtkWidget* create_parametres_ (void);
GtkWidget* create_ajouter_parametres (void);
GtkWidget* create_acceuil (void);
GtkWidget* create_gestion (void);
GtkWidget* create_fenetre_menu (void);
GtkWidget* create_fenetre_ajouter (void);
GtkWidget* create_fenetre_afficher (void);
GtkWidget* create_fenetre_rechercher1 (void);
GtkWidget* create_fenetre_rechercher2 (void);
GtkWidget* create_fenetre_modifier (void);
GtkWidget* create_fenetre_plusreclame (void);
