/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_gestion_capteur (void);
GtkWidget* create_ajouter_capteur (void);
GtkWidget* create_modifier_capteur (void);
GtkWidget* create_supprimer_capteur (void);
GtkWidget* create_parametres_ (void);
GtkWidget* create_ajouter_parametres (void);
